#!/usr/bin/env bash
# sync-upstream.sh — semi-automated upstream sync for valadrien-os.
#
# Runs the same pipeline used for the 2026-07 catch-up sync:
#   1. fetch upstream, create sync/upstream-<date> branch off master
#   2. merge upstream/master (no commit)
#   3. mechanical resolution:
#        - fork-identity docs stay ours (README/AGENTS/DESIGN/CONTRIBUTING)
#        - scripts/release.sh stays ours (disabled stub)
#        - pnpm-lock.yaml -> upstream (regenerated by pnpm install later)
#        - everything else -> upstream side staged
#   4. rebrand codemod over the tree (scripts/sync/rebrand-codemod.py)
#   5. rename-normalized 3-way re-merge for every conflicted file
#      (scripts/sync/three-way-resolve.py) so fork FEATURE code is preserved,
#      not just branding
#   6. report: remaining real conflicts (markers) -> human/Claude Code;
#      if zero -> pnpm install + typecheck; commit branch on success
#   7. ntfy notification either way
#
# NEVER pushes to or merges into master. Review the sync branch, run the
# test suite, deploy to staging, then fast-forward/merge master yourself.
#
# Env: NTFY_TOPIC, NTFY_SERVER (default https://ntfy.sh)
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
NTFY_SERVER="${NTFY_SERVER:-https://ntfy.sh}"
DATE_TAG="$(date +%Y%m%d)"
BRANCH="sync/upstream-$DATE_TAG"

notify() { # title, body, tags
  [[ -n "${NTFY_TOPIC:-}" ]] || return 0
  curl -fsS -m 10 -H "Title: $1" -H "Tags: $3" -d "$2" \
    "$NTFY_SERVER/$NTFY_TOPIC" >/dev/null 2>&1 || true
}

cd "$REPO_DIR"
git remote get-url upstream >/dev/null 2>&1 || \
  git remote add upstream https://github.com/paperclipai/paperclip.git
git fetch upstream master --quiet

BEHIND=$(git rev-list --count master..upstream/master)
if [[ "$BEHIND" -eq 0 ]]; then
  echo "Already up to date with upstream."
  exit 0
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree not clean — aborting." >&2
  notify "valadrien-os sync ABORTED" "Working tree not clean." "warning"
  exit 1
fi

MERGE_BASE=$(git merge-base master upstream/master)
git checkout -B "$BRANCH" master

# ---- merge + mechanical resolution ----------------------------------------
git merge --no-commit --no-ff upstream/master >/dev/null 2>&1 || true
git diff --name-only --diff-filter=U > /tmp/sync-conflicts-raw.txt
NCONF=$(wc -l < /tmp/sync-conflicts-raw.txt | tr -d ' ')
echo "merge: $BEHIND commits, $NCONF conflicted files"

# identity docs + disabled release stub stay ours
for f in README.md AGENTS.md DESIGN.md CONTRIBUTING.md scripts/release.sh; do
  git checkout --ours -- "$f" 2>/dev/null && git add -- "$f" 2>/dev/null || true
done
# lockfile from upstream; regenerated after codemod
git checkout --theirs -- pnpm-lock.yaml 2>/dev/null && git add pnpm-lock.yaml || true
# remaining conflicts: upstream side where it exists, ours otherwise
for f in $(git diff --name-only --diff-filter=U); do
  if git cat-file -e "upstream/master:$f" 2>/dev/null; then
    git checkout --theirs -- "$f"
  else
    git checkout --ours -- "$f" 2>/dev/null || git rm -q -- "$f"
  fi
  git add -- "$f" 2>/dev/null || true
done

# ---- rebrand codemod -------------------------------------------------------
python3 "$SCRIPT_DIR/rebrand-codemod.py" "$REPO_DIR"

# ---- rename-normalized 3-way pass (preserves fork feature code) ------------
python3 "$SCRIPT_DIR/three-way-resolve.py" \
  /tmp/sync-conflicts-raw.txt "$MERGE_BASE" master upstream/master \
  | tee /tmp/sync-3way-report.txt

git add -A
MARKERS=$(grep -rl '^<<<<<<<' --include='*' . --exclude-dir=.git --exclude-dir=node_modules 2>/dev/null | grep -v scripts/sync/ | wc -l | tr -d ' ')

if [[ "$MARKERS" -gt 0 ]]; then
  git commit -m "WIP sync $DATE_TAG: $BEHIND upstream commits, $MARKERS files need manual conflict resolution" >/dev/null
  echo "== $MARKERS files still carry conflict markers — resolve with Claude Code, see scripts/sync/sync-conflicts.txt =="
  notify "valadrien-os sync: manual step needed" \
    "$BEHIND commits merged onto $BRANCH; $MARKERS files need feature-conflict resolution. Open Claude Code on the repo." \
    "construction"
  exit 2
fi

# ---- verify ----------------------------------------------------------------
pnpm install >/tmp/sync-install.log 2>&1 || {
  notify "valadrien-os sync: pnpm install FAILED" "See /tmp/sync-install.log on $(hostname)." "x"
  exit 1
}
git add pnpm-lock.yaml
pnpm typecheck >/tmp/sync-typecheck.log 2>&1
TC=$?
git commit -m "Sync upstream: $BEHIND commits from paperclipai/paperclip ($DATE_TAG)" >/dev/null

if [[ $TC -ne 0 ]]; then
  ERRS=$(grep -c 'error TS' /tmp/sync-typecheck.log || true)
  notify "valadrien-os sync: typecheck FAILED ($ERRS errors)" \
    "Branch $BRANCH committed but typecheck fails. Fix before merging to master." "x"
  echo "typecheck failed — see /tmp/sync-typecheck.log"
  exit 1
fi

notify "valadrien-os sync READY: $BRANCH" \
  "$BEHIND upstream commits merged, codemod applied, typecheck clean. Review, run tests + staging deploy, then merge to master." \
  "white_check_mark"
echo "Sync branch $BRANCH ready. Next: pnpm test:run, staging deploy, merge to master."
